import { useEffect, useMemo, useState } from "react";
import { Activity, CheckCircle2, ClipboardList, Factory, Gauge, PackageCheck, Plus, Search, ShieldCheck, Thermometer, X } from "lucide-react";
import { toast } from "sonner";
import { trpc } from "@/lib/trpc";

type ProductionWorkbenchProps = { onClose: () => void };

const steps = ["Mistura", "Prensagem", "Cura", "Usinagem", "Inspeção", "Expedição"];

export default function ProductionWorkbench({ onClose }: ProductionWorkbenchProps) {
  const [activeTab, setActiveTab] = useState("overview");
  const [showNewOrder, setShowNewOrder] = useState(false);
  const [search, setSearch] = useState("");
  const [productCode, setProductCode] = useState("BP-AX-001");
  const [quantity, setQuantity] = useState("1200");
  const [customer, setCustomer] = useState("Scorpios Automotive");
  const utils = trpc.useUtils();
  const { data: orders = [], isLoading } = trpc.production.orders.useQuery({ search: search || undefined });
  const { data: materials = [] } = trpc.production.materialLots.useQuery();
  const bootstrap = trpc.production.bootstrap.useMutation({ onSuccess: () => { utils.production.orders.invalidate(); utils.production.materialLots.invalidate(); } });
  const createOrder = trpc.production.createOrder.useMutation({ onSuccess: () => { utils.production.orders.invalidate(); setShowNewOrder(false); toast.success("Ordem de produção criada", { description: "A rastreabilidade do lote foi iniciada." }); } });
  const updateStatus = trpc.production.updateOrderStatus.useMutation({ onSuccess: () => utils.production.orders.invalidate() });
  const filteredOrders = useMemo(() => orders, [orders]);

  useEffect(() => {
    if (!orders.length && !materials.length && !bootstrap.isPending && !bootstrap.isSuccess) bootstrap.mutate();
  }, [orders.length, materials.length, bootstrap.isPending, bootstrap.isSuccess]);

  const submitOrder = () => {
    createOrder.mutate({ productCode, quantity: Number(quantity), customer, dueDate: new Date(Date.now() + 7 * 86400000) });
  };

  return <div className="production-overlay"><div className="production-shell">
    <header className="production-topbar"><div className="production-brand"><Factory size={18} /><div><span>INTEGRATED MANUFACTURING SYSTEM</span><strong>Brake Pad Operations</strong></div></div><div className="production-top-actions"><span className="synthetic-label"><span className="pulse-dot" /> MODELO INDUSTRIAL</span><button className="detail-close" onClick={onClose} aria-label="Fechar produção"><X size={18} /></button></div></header>
    <div className="production-content">
      <div className="production-heading"><div><span className="detail-heading-kicker"><span className="heading-accent" /> SCORPIOS METALWORKS · GEM-01</span><h1>Produção de pastilhas<span>.</span></h1><p>Planejamento, execução e rastreabilidade do processo de fabricação.</p></div><button className="production-primary" onClick={() => setShowNewOrder(true)}><Plus size={15} /> Nova ordem</button></div>
      <nav className="production-tabs">{[["overview","Visão geral"],["orders","Ordens de produção"],["traceability","Rastreabilidade"],["quality","Qualidade & processo"]].map(([id,label]) => <button key={id} className={activeTab === id ? "active" : ""} onClick={() => setActiveTab(id)}>{label}</button>)}</nav>
      {activeTab === "overview" && <>
        <section className="production-kpis"><div><span>ORDENS EM PRODUÇÃO</span><strong>{orders.filter((o) => o.status === "Em produção").length.toString().padStart(2,"0")}</strong><small><Activity size={12} /> +2 nesta semana</small></div><div><span>OEE DA LINHA</span><strong>78.4<span>%</span></strong><small className="good"><Gauge size={12} /> acima do gate 75%</small></div><div><span>FPY · FIRST PASS YIELD</span><strong>94.8<span>%</span></strong><small className="good"><CheckCircle2 size={12} /> +3.2 pp no ciclo</small></div><div><span>LOTES EM QUARENTENA</span><strong className="warning">02</strong><small className="warning"><ShieldCheck size={12} /> requer análise</small></div></section>
        <section className="production-grid"><div className="production-panel process-panel"><div className="production-panel-head"><div><span className="section-kicker">FLUXO PRODUTIVO</span><h2>Estado da linha</h2></div><span className="live-chip">LIVE</span></div><div className="process-line">{steps.map((step, index) => <div className={`process-node ${index < 3 ? "done" : index === 3 ? "current" : ""}`} key={step}><span>{index < 3 ? "✓" : index + 1}</span><strong>{step}</strong><small>{index < 3 ? "Conforme" : index === 3 ? "Em execução" : "Aguardando"}</small></div>)}</div><div className="line-metrics"><span><Thermometer size={14} /> Cura: <strong>182°C</strong></span><span><Gauge size={14} /> Prensa: <strong>42 bar</strong></span><span><PackageCheck size={14} /> FPY: <strong>94.8%</strong></span></div></div><div className="production-panel shift-panel"><div className="production-panel-head"><div><span className="section-kicker">TURNO ATUAL</span><h2>Performance da célula</h2></div><span className="status-pill status-pill-green">Estável</span></div><div className="shift-main"><strong>1.248</strong><span>peças boas produzidas</span></div><div className="shift-bars">{[42,58,48,76,62,88,74,92,81,96].map((height,index) => <i key={index} style={{height: `${height}%`}} />)}</div><div className="shift-footer"><span>Meta do turno <strong>1.500</strong></span><span>Refugo <strong className="warning-text">3.4%</strong></span></div></div></section>
        <section className="production-panel orders-preview"><div className="production-panel-head"><div><span className="section-kicker">EXECUÇÃO</span><h2>Ordens recentes</h2></div><button className="text-action" onClick={() => setActiveTab("orders")}>Ver todas ↗</button></div><OrderTable orders={filteredOrders.slice(0, 4)} onStatusChange={(id, status) => updateStatus.mutate({ id, status })} /></section>
      </>}
      {activeTab === "orders" && <section className="production-panel full-panel"><div className="production-panel-head"><div><span className="section-kicker">PRODUCTION CONTROL</span><h2>Ordens de produção</h2></div><div className="production-search"><Search size={14} /><input value={search} onChange={(e) => setSearch(e.target.value)} placeholder="Buscar OP, produto ou cliente..." /></div></div>{isLoading ? <div className="production-empty">Carregando ordens...</div> : <OrderTable orders={filteredOrders} onStatusChange={(id, status) => updateStatus.mutate({ id, status })} />}</section>}
      {activeTab === "traceability" && <section className="production-grid"><div className="production-panel full-panel"><div className="production-panel-head"><div><span className="section-kicker">MATERIAL TRACEABILITY</span><h2>Lotes de matéria-prima</h2></div><span className="status-pill status-pill-cyan">ISO 9001</span></div><div className="material-list">{materials.map((lot) => <div className="material-row" key={lot.id}><div className="material-icon"><PackageCheck size={16} /></div><div><strong>{lot.material}</strong><span>{lot.lotCode} · fornecedor {lot.supplier}</span></div><span className={`material-status ${lot.status === "Liberado" ? "released" : "hold"}`}>{lot.status}</span><small>{new Date(lot.receivedAt).toLocaleDateString("pt-BR")}</small></div>)}</div></div><div className="production-panel full-panel trace-card"><span className="section-kicker">GENEALOGIA DO PRODUTO</span><h2>Selecione uma OP</h2><p>Consulte matéria-prima, parâmetros de processo, inspeções e expedição associados a cada lote.</p><button className="production-secondary" onClick={() => toast.info("Rastreabilidade pronta", { description: "Selecione uma ordem para abrir a genealogia completa." })}>Abrir genealogia</button></div></section>}
      {activeTab === "quality" && <section className="production-grid"><div className="production-panel full-panel"><div className="production-panel-head"><div><span className="section-kicker">QUALITY CONTROL PLAN</span><h2>Características críticas do produto</h2></div><span className="status-pill status-pill-green">94.8% FPY</span></div><div className="quality-grid">{[["Espessura","12.00 ± 0.15 mm","11.98 mm","Conforme"],["Dureza Rockwell","85 ± 5 HRB","87 HRB","Conforme"],["Compressibilidade","≤ 2.0%","1.6%","Conforme"],["Cisalhamento","≥ 1.5 MPa","1.32 MPa","Atenção"]].map(([name,spec,value,status]) => <div className="quality-card" key={name}><span>{name}</span><strong>{value}</strong><small>Especificação: {spec}</small><b className={status === "Conforme" ? "good" : "warning"}>{status}</b></div>)}</div></div><div className="production-panel full-panel"><span className="section-kicker">ALERTAS DE QUALIDADE</span><h2>Gates pendentes</h2><div className="alert-quality"><ShieldCheck size={17} /><div><strong>Lote MP-2026-0912 em quarentena</strong><span>Resistência ao cisalhamento abaixo do limite em amostra inicial.</span></div></div><div className="alert-quality"><Thermometer size={17} /><div><strong>Cura CP-04 requer calibração</strong><span>Desvio de +4°C detectado no último ciclo.</span></div></div></div></section>}
    </div>
    {showNewOrder && <div className="production-modal-backdrop"><section className="production-modal"><div className="production-panel-head"><div><span className="section-kicker">PLANEJAMENTO</span><h2>Nova ordem de produção</h2></div><button onClick={() => setShowNewOrder(false)}><X size={17} /></button></div><div className="production-form"><label>Produto<select value={productCode} onChange={(e) => setProductCode(e.target.value)}><option value="BP-AX-001">BP-AX-001 · Pastilha eixo dianteiro</option><option value="BP-HT-002">BP-HT-002 · Pastilha high temperature</option><option value="BP-EC-003">BP-EC-003 · Pastilha econômica</option></select></label><label>Quantidade<input type="number" min="1" value={quantity} onChange={(e) => setQuantity(e.target.value)} /></label><label>Cliente<input value={customer} onChange={(e) => setCustomer(e.target.value)} /></label></div><div className="production-modal-foot"><small>Será criado um lote rastreável com roteiro padrão de 6 etapas.</small><button className="production-primary" onClick={submitOrder} disabled={createOrder.isPending}><Plus size={14} /> {createOrder.isPending ? "Criando..." : "Criar ordem"}</button></div></section></div>}
  </div></div>;
}

function OrderTable({ orders, onStatusChange }: { orders: Array<{ id: number; orderCode: string; productCode: string; quantity: number; customer: string; status: string; currentStep: string; dueDate: Date | string }>; onStatusChange: (id: number, status: "Planejada" | "Em produção" | "Em inspeção" | "Concluída" | "Quarentena") => void }) {
  if (!orders.length) return <div className="production-empty">Nenhuma ordem encontrada.</div>;
  return <div className="order-table-wrap"><table className="order-table"><thead><tr><th>Ordem</th><th>Produto</th><th>Cliente</th><th>Quantidade</th><th>Etapa atual</th><th>Prazo</th><th>Status</th></tr></thead><tbody>{orders.map((order) => <tr key={order.id}><td><strong>{order.orderCode}</strong></td><td>{order.productCode}</td><td>{order.customer}</td><td>{order.quantity.toLocaleString("pt-BR")}</td><td>{order.currentStep}</td><td>{new Date(order.dueDate).toLocaleDateString("pt-BR")}</td><td><select className={`order-status order-status-${order.status.toLowerCase().replaceAll(" ", "-")}`} value={order.status} onChange={(e) => onStatusChange(order.id, e.target.value as "Planejada" | "Em produção" | "Em inspeção" | "Concluída" | "Quarentena")}><option>Planejada</option><option>Em produção</option><option>Em inspeção</option><option>Concluída</option><option>Quarentena</option></select></td></tr>)}</tbody></table></div>;
}
